/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchaseIdRouteImport } from './routes/purchase.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIdRoute = PurchaseIdRouteImport.update({
  id: '/purchase/$id',
  path: '/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/advertising': typeof AdvertisingRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/financing': typeof FinancingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/service': typeof ServiceRoute
  '/users': typeof UsersRoute
  '/purchase/$id': typeof PurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/advertising': typeof AdvertisingRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/financing': typeof FinancingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/service': typeof ServiceRoute
  '/users': typeof UsersRoute
  '/purchase/$id': typeof PurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/advertising': typeof AdvertisingRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/financing': typeof FinancingRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/service': typeof ServiceRoute
  '/users': typeof UsersRoute
  '/purchase/$id': typeof PurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/advertising'
    | '/customers'
    | '/dashboard'
    | '/financing'
    | '/inventory'
    | '/login'
    | '/marketing'
    | '/orders'
    | '/register'
    | '/reports'
    | '/sales'
    | '/service'
    | '/users'
    | '/purchase/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/advertising'
    | '/customers'
    | '/dashboard'
    | '/financing'
    | '/inventory'
    | '/login'
    | '/marketing'
    | '/orders'
    | '/register'
    | '/reports'
    | '/sales'
    | '/service'
    | '/users'
    | '/purchase/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/advertising'
    | '/customers'
    | '/dashboard'
    | '/financing'
    | '/inventory'
    | '/login'
    | '/marketing'
    | '/orders'
    | '/register'
    | '/reports'
    | '/sales'
    | '/service'
    | '/users'
    | '/purchase/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdvertisingRoute: typeof AdvertisingRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  FinancingRoute: typeof FinancingRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  ServiceRoute: typeof ServiceRoute
  UsersRoute: typeof UsersRoute
  PurchaseIdRoute: typeof PurchaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$id': {
      id: '/purchase/$id'
      path: '/purchase/$id'
      fullPath: '/purchase/$id'
      preLoaderRoute: typeof PurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdvertisingRoute: AdvertisingRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  FinancingRoute: FinancingRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  ServiceRoute: ServiceRoute,
  UsersRoute: UsersRoute,
  PurchaseIdRoute: PurchaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
